# Generated by Django 5.0.1 on 2024-01-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weathercache_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='timestamp',
            new_name='created',
        ),
    ]
